{
 "title": "Istio USE Dashboard",
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "query_result(sum(istio_requests_total) by (destination_workload_namespace) or sum(istio_tcp_sent_bytes_total) by (destination_workload_namespace))"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage by Pod",
   "type": "graph",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate (container_cpu_usage_seconds_total{namespace=\"$namespace\",pod_name=~\".*\",container_name!~\"POD|istio-proxy\"}[1m]) * 100) by (pod_name)"
    }
   ]
  },
  {
   "title": "Memory Usage by Pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod_name=~\".*\",container_name!~\"POD|istio-proxy\"}) by (pod_name)"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate (container_network_receive_bytes_total{namespace=\"$namespace\",pod_name=~\".*\"}[1m])) ",
     "legendFormat": "received"
    },
    {
     "expr": "-sum (rate (container_network_transmit_bytes_total{namespace=\"$namespace\",pod_name=~\".*\"}[1m]))",
     "legendFormat": "transmited"
    }
   ]
  }
 ]
}